export const data = {
    title: "##ocr_text## | ##class## | ##chapter## | ##subject## | ##book## | Doubtnut",
    description: "##ocr_text##\nClass:##class##\nSubject: ##subject##\nChapter: ##chapter##\nBook:##book##\nBoard:##board##\n\nYou can ask any doubt from class 6-12, JEE, NEET, Teaching, SSC, Defense and Banking exam on  Doubtnut App or You can Whatsapp us at - 8400400400\n" +
          "Link -  https://doubtnut.app.link/2um0jr7Joeb​\n\nContact Us:\n👉 Have Any Query? Ask Us.\n🤙 Call: 01247158250\n💬 WhatsApp: 8400400400\n📧 Email: info@doubtnut.com\n🌐 Website: https://www.doubtnut.com\n\n" +
          "Welcome to Doubtnut.\nDoubtnut is World’s Biggest Platform for Video Solutions of Physics, Chemistry, Maths and Biology Doubts with over 5 million+ Video Solutions. Doubtnut is a Q&A App for Maths, Physics, Chemistry and Biology (up to JEE Advanced and NEET Level), Where You Can Ask Unlimited Questions by Clicking a Picture of Doubt on the Doubtnut App and Get Instant Video Solution.\n\n" +
          "Subscribe Our YouTube Channels:\n✿ Doubtnut: https://www.youtube.com/channel/UCcv7pspGHmM7AOywuLM1ufA?sub_confirmation=1\n✿ Class 11-12, JEE & NEET (Hindi): https://www.youtube.com/channel/UCiIrZf4bn1i0IOf8YgSMzWA?sub_confirmation=1\n✿ Class 11-12, JEE & NEET (English):: https://www.youtube.com/channel/UCbJ_xe2bMLo9yuBC-i_13MQ?sub_confirmation=1\n✿ Class 6-10 (Hindi): https://www.youtube.com/channel/UCZnV1hkn5A3fdpTOVi60tzg?sub_confirmation=1\n✿ Class 6-10 (English): https://www.youtube.com/channel/UC9KeHSWOEBXIrbWYasHeSyg?sub_confirmation=1\n✿ Doubtnut Govt. Exams: https://www.youtube.com/channel/UCWPaROsU_06MSqiZ_O6zaVg?sub_confirmation=1\n\n" +
          "Follow Us:\n🔔 Facebook: https://www.facebook.com/doubtnut\n🔔 Instagram: https://www.instagram.com/doubtnut\n🔔 Telegram: https://t.me/DoubtnutOfficial\n🔔 Twitter: https://twitter.com/DoubtnutApp\n🔔 LinkedIn: https://www.linkedin.com/company/doubtnut\n\n" +
          "Our Telegram Pages:\n🔔 Doubtnut Official: https://t.me/DoubtnutOfficial\n🔔 Doubtnut IIT JEE: https://t.me/DoubtnutIITJEE\n🔔 Doubtnut NEET: https://t.me/Doubtnut_NEET\n🔔 Doubtnut CBSE Boards: https://t.me/DoubtnutCBSEBoards\n🔔 Doubtnut UP Boards: https://t.me/DoubtnutUPBoards\n🔔 Doubtnut Bihar Boards: https://t.me/DoubtnutBiharBoards\n🔔 Doubtnut Government Exams: https://t.me/DoubtnutGovernmentExams\n" +
          "##keywords_by_class##\n\n" +
          "##books_name##",
    keywords: {
        12: [
            "class 12",
            "class 12 physics",
            "class 12 chemistry",
            "class 12 english",
            "class 12 maths",
            "class 12 biology",
            "cbse class 12 result",
            "class 12 economics",
            "class 12 accountancy",
            "class 12 syllabus physics",
            "cbse class 12",
            "class 12 english grammar",
            "class 12 syllabus cbse",
            "class 12 history",
            "class 12 geography",
            "class 12 ncert",
            "class 12 syllabus",
            "cbse class 12 maths",
            "cbse class 12 english",
            "cbse class 12 physics",
            "cbse class 12 chemistry",
            "class 12 grammar",
            "cbse class 12 biology",
            "cbse class 12 commerce",
            "cbse class 12 accountancy",
            "class 12 syllabus chemistry",
            "class 12 grammar syllabus",
            "class 12 syllabus maths",
            "class 12 latest syllabus",
            "class 12 syllabus english",
            "class 12 syllabus biology",
            "class 12 syllabus of physics",
            "class 12 syllabus of chemistry",
            "class 12 syllabus science",
            "class 12 syllabus ncert",
            "class 12 syllabus of english",
            "class 12 syllabus commerce",
        ],
        11: [
            "class 11",
            "class 11 organic chemistry",
            "class 11 physics",
            "class 11 chemistry",
            "class 11 maths",
            "class 11 english",
            "class 11 economics",
            "class 11 biology",
            "class 11 statistics",
            "class 11 syllabus physics",
            "class 11 commerce",
            "class 11 syllabus chemistry",
            "class 11 ncert economics",
            "class 11 ncert",
            "class 11 syllabus cbse",
            "class 11 syllabus maths",
            "cbse class 11",
            "class 11 english grammar",
            "class 11 syllabus",
            "class 11 science",
            "class 11 syllabus english",
            "class 11 syllabus 2020-21",
            "cbse class 11 maths",
            "cbse class 11 physics",
            "cbse class 11 books",
            "cbse class 11 english",
            "cbse class 11 chemistry",
            "cbse class 11 biology",
            "cbse class 11 accountancy",
            "cbse class 11 commerce",
            "cbse class 11 science",
            "class 11 syllabus biology",
            "cbse class 11 statistics",
            "class 11 syllabus ncert",
            "class 11 syllabus of english",
            "class 11 syllabus science",
            "class 11 syllabus commerce",
        ],
        10: [
            "class 10 maths",
            "class 10",
            "class 10 science",
            "class 10 english",
            "cbse class 10",
            "class 10 chemistry",
            "class 10 english grammar",
            "class 10 biology",
            "class 10 physics",
            "class 10 ncert",
            "sst class 10",
            "class 10 geography",
            "class 10 syllabus cbse",
            "class 10 history",
            "class 10 syllabus",
            "cbse class 10 maths",
            "cbse class 10 board exam",
            "class 10 syllabus english",
            "class 10 syllabus of science",
            "class 10 syllabus science",
            "class 10 syllabus maths",
            "cbse class 10 exam date 2021",
            "cbse class 10 sample paper 2021",
            "cbse class 10 science",
            "cbse class 10 english",
            "class 10 board exam 2021",
            "cbse class 10 board",
            "cbse class 10 physics",
            "cbse class 10 chemistry",
            "cbse class 10 biology",
            "cbse class 10 english grammar",
            "cbse class 10 2021",
            "class 10 syllabus 2021",
            "class 10 syllabus ncert",
            "class 10 syllabus of english",
            "class 10 syllabus of maths",
            "class 10 syllabus physics",
            "class 10 syllabus sst 2021",
        ],
        9: [
            "class 9 math",
            "class 9",
            "class 9 science",
            "class 9 english",
            "class 9 ncert",
            "class 9 physics",
            "class 9 geography",
            "sst class 9",
            "class 9 chemistry",
            "class 9 history",
            "class 9 biology",
            "class 9 syllabus cbse",
            "cbse class 9",
            "cbse class 9 maths",
            "class 9 english grammar",
            "class 9 syllabus",
            "cbse class 9 science",
            "class 9 syllabus maths",
            "class 9 syllabus ncert",
            "class 9 syllabus science",
            "class 9 syllabus english",
            "cbse class 9 english",
            "cbse class 9 physics",
            "cbse class 9 biology",
            "class 9 s.s.t syllabus",
            "cbse class 9 chemistry",
            "class 9 syllabus 2021",
            "cbse class 9 grammar",
            "class 9 syllabus of english",
            "class 9 syllabus of maths",
            "class 9 life science syllabus",
            "class 9 syllabus cbse maths",
            "class 9 syllabus science ncert",
            "class 9 syllabus maths cbse",
            "class 9 syllabus for cbse",
            "class 9 syllabus maths ncert",
            "class 9 syllabus physics",
        ],
        8: [
            "class 8 maths",
            "class 8",
            "class 8 science",
            "class 8 ncert science",
            "class 8 english",
            "class 8 ncert",
            "class 8 ncert history",
            "class 8 history",
            "sst class 8",
            "class 8 ncert geography",
            "class 8 geography",
            "cbse class 8 maths",
            "cbse class 8",
            "cbse class 8 science",
            "class 8 biology",
            "class 8 physics",
            "class 8 syllabus",
            "cbse class 8 books",
            "cbse class 8 english",
            "class 8 syllabus ncert",
            "class 8 syllabus cbse",
            "class 8 syllabus cbse maths",
            "cbse class 8 ncert",
            "cbse class 8 geography",
            "cbse class 8 chemistry",
            "class 8 syllabus math",
            "cbse class 8 physics",
            "class 8 syllabus science",
            "class 8 syllabus 2021",
            "cbse class 8 ncert solutions",
            "class 8 physics syllabus",
            "cbse class 8 biology",
            "class 8 geography syllabus",
            "cbse class 8 grammar",
            "class 8 syllabus english",
            "class 8 full syllabus",
            "class 8 syllabus of science",
            "class 8 cbse physics syllabus",
            "class 8 syllabus of english",
            "class 8 syllabus of maths",
            "class 8 syllabus book",
            "class 8 syllabus of 2021",
            "class 8 syllabus of sst",
            "class 8 syllabus science ncert",
            "class 8 syllabus ncert english",
            "class 8 syllabus social science",
            "class 8 syllabus cbse science",
            "class 8 syllabus cbse board",
        ],
        7: [
            "class 7 math",
            "class 7",
            "class 7 science",
            "class 7 english",
            "class 7 ncert science",
            "class 7 ncert book",
            "class 7 ncert history",
            "class 7 ncert geography",
            "class 7 history",
            "class 7 geography",
            "cbse class 7 maths",
            "sst class 7",
            "class 7 english grammar",
            "cbse class 7 science",
            "cbse class 7 english",
            "books of class 7 cbse",
            "class 7 physics",
            "class 7 syllabus",
            "class 7 biology",
            "class 7 syllabus ncert",
            "class 7 syllabus cbse",
            "class 7 syllabus of cbse",
            "class 7 english grammar syllabus",
            "class 7 sst syllabus",
            "class 7 syllabus maths",
            "class 7 history syllabus",
            "class 7 computer syllabus",
            "class 7 geography syllabus",
            "class 7 syllabus science",
            "class 7 syllabus 2021",
            "class 7 syllabus english",
            "class 7 syllabus of maths",
            "class 7 syllabus of english",
            "class 7 syllabus of science",
            "class 7 syllabus of 2021",
            "class 7 syllabus science cbse",
            "class 7 science syllabus 2021",
            "cbse class 7",
        ],
        6: [
            "class 6 maths",
            "class 6 ncert history",
            "class 6 ncert geography",
            "class 6 ncert book",
            "class 6 science",
            "class 6 ncert maths",
            "class 6 ncert science",
            "class 6 english",
            "class 6",
            "class 6 ncert",
            "class 6 history",
            "class 6 geography",
            "cbse class 6 books",
            "cbse class 6 maths",
            "books of class 6 cbse",
            "sst class 6",
            "class 6 book",
            "cbse class 6 science",
            "class 6 syllabus maths",
            "cbse class 6 english",
            "class 6 syllabus",
            "syllabus for class 6",
            "syllabus of class 6 cbse",
            "class 6 syllabus cbse",
            "ncert class 6 syllabus",
            "cbse class 6 english grammar",
            "syllabus for class 6 science",
            "cbse class 6 geography",
            "class 6 english grammar syllabus",
            "class 6 syllabus ncert",
            "cbse board class 6 science",
            "class 6 syllabus science",
            "cbse class 6 physics",
            "class 6 syllabus english",
            "class 6 syllabus of maths",
            "cbse calss 6",
            "cbse class 6 maths in english",
            "class 6 syllabus of sst",
            "class 6 syllabus of english",
            "class 6 syllabus history",
            "class 6 english grammar syllabus 2021",
            "class 6 syllabus in maths",
            "class 6 syllabus ncert science",
            "class 6 syllabus ncert 2021",
            "class 6 syllabus all subject",
            "class 6 syllabus maths cbse",
            "6 class ka math syllabus",
        ],
    },
};
